### ISSUE TITLE
AFL++ Container Immediately Exits upon creation

### ISSUE THREAD

**Issue by Sankalpsp21** [alex-maleno/Fuzzing-Module#2]
I'm on the step "How to create an AFL++ Docker Container" and when I try to run the container it immediately exits saying "EXITED (0)"

##The downloaded image:
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/79608516/219829609-5c20e61e-6c27-403c-91f8-30f2351252a8.png">

##When I run it:
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/79608516/219829631-e7cda234-446d-4d88-a863-96cf438258cc.png">

##Trying to start the container:
https://user-images.githubusercontent.com/79608516/219829655-cae76b95-66ac-49eb-bbc1-d534d8cee2e4.mov

I downloaded the image using "docker pull aflplusplus/aflplusplus"
Is there something I'm missing?

**Comment by mathisfoxius** [comment]
I ran into the same problem. How did you manage to solve it? :)  @Sankalpsp21
